workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: 3.19.5

    scripts:
      - name: Generate .env file
        script: |
          rm -f .env
          printenv | grep '^ENV_' | sed 's/^ENV_//' >> .env

      - name: Get dependencies
        script: flutter pub get

      - name: Build debug APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
